#!/bin/bash

GRUN="java -classpath ../lib/symtab.jar:../lib/antlr-denter-1.2-SNAPSHOT.jar:/usr/local/Cellar/antlr/4.2/antlr-4.2-complete.jar:. org.antlr.v4.runtime.misc.TestRig"

if [ ! -d "output" ]; then
  echo "Not 'output' directory"
  exit -1
fi

cd output

$GRUN webscript program ../$1
